String newtype
gcfbn/learning_rust pull request #106
Opened 2021-08-09 18:50 UTC by gcfbn

2021-08-10 14:21 UTC, pdodev commented on string-newtype/src/lib.rs
> +        MyString(s.to_string())
it looks better this way: s.to_owned()

2021-08-10 14:28 UTC, pdodev commented on string-newtype/src/lib.rs
> +}
Tego nie potrzebujesz. Masz już:
```rust
impl From<String> for MyString 
```

2021-08-10 14:42 UTC, pdodev commented on string-newtype/src/lib.rs
> +            let _ = Vec::from(vec_of_refs);
Dlaczego uważasz, że tworzysz tutaj vector z newtype-ami ?
Spróbuj skompilować:
```rust
let  _check: Vec<MyString> = Vec::from(vec_of_refs);
```
i zobacz jaki dostaniesz komunikat.

2021-08-10 14:43 UTC, pdodev commented on string-newtype/src/lib.rs
> +            let _ = Vec::from(vec_of_slices);
to samo co wyżej - dlaczego uważasz, że tworzysz tutaj vector z newtype-ami ?

2021-08-10 14:43 UTC, pdodev commented on string-newtype/src/lib.rs
> +            let _ = Vec::from(vec_of_refs);
to samo co wyżej - dlaczego uważasz, że tworzysz tutaj vector z newtype-ami ?

2021-08-10 14:44 UTC, pdodev commented on string-newtype/src/lib.rs
> +            let _ = Vec::from(array);
to samo co wyżej - dlaczego uważasz, że tworzysz tutaj vector z newtype-ami ?

2021-08-10 14:45 UTC, pdodev commented on string-newtype/src/lib.rs
> +            let _ = Vec::from(array);
o samo co wyżej - dlaczego uważasz, że tworzysz tutaj vector z newtype-ami ?

2021-08-10 14:45 UTC, pdodev commented on string-newtype/src/lib.rs
> +            let _ = Vec::from(ref_to_vec.clone());
o samo co wyżej - dlaczego uważasz, że tworzysz tutaj vector z newtype-ami ?

2021-08-10 14:47 UTC, pdodev requested changes
Please, fix some tests

2021-08-11 19:05 UTC, gcfbn commented
Rzeczywiście, poprzednie testy niewiele sprawdzały, nie przejrzałem ich drugi raz przez zrobieniem push-a. Tutaj lepszego pomysłu niż mapowanie iteratora nie mam, bo automatycznego castowania pomiędzy typami uzyskać się na pewno nie da.

2021-08-12 18:49 UTC, merged