Add logging - default or user-defined
gcfbn/learning_rust pull request #113
Opened 2021-08-16 20:45 UTC by gcfbn

Code might look better (I think `#[cfg(not(feature = "simple_logging"))]` could be simplified). Generally, is it a good way of using cargo features?

2021-08-17 11:38 UTC, pdodev commented
>I think #[cfg(not(feature = "simple_logging"))] could be simplified
Not really - at least I don't know any other option ...

2021-08-17 12:49 UTC, pdodev commented
Please have a look at this: https://crates.io/crates/cfg-if

2021-08-17 13:30 UTC, pdodev requested changes
- how would you like to use the DefaultLogger struct and its write_message method ?
- if I don't use feature "flexi_logger", I have to implement the AppLogger trait.
  I think it can be supprising to the user of the utils crate (I got an error message ...).
- I think we need something like this (maybe better name is: simple_logging->default_logging):

```rust
  fn main(&self) -> i32 {
      configure_logging();
  }

  fn configure_logging() {
      #[cfg(feature = "simple_logging")] {
        flexi_logger::Logger::try_with_env().unwrap().log_to_stdout().start().unwrap();
        trace!("Default logger initialized");
      }
  }
```

  In case when simple_logging is not defined we will have an empty implementation of the configure_logging mehtod.
  The user still has the option to implement his own version of this method. 

- please implement an example application:
  RUST_LOG=info cargo run --example use_simple_logging
  RUST_LOG=info cargo run --example use_simple_logging --features simple_logging

  e.g:

```rust

    use anyhow::{Error as aError, Result as aResult};
    use cmd_args::CmdArgs;
    use log::info;
    use thiserror::Error;
    use utils::ApplicationRunner;

    /// Main function that is called when the app starts
    ///
    /// Calls run() function and kills process if it returns an error
    fn main() {
        App.main();
    }

    struct App;

    impl ApplicationRunner for App {
        type CmdArgs = CmdArgs;
        type Error = AppError;

        fn run(&self, _cmd_args: CmdArgs) -> Result<(), Self::Error> {
            println!("hello");
            info!("info -> hello");
            Ok(())
        }
    }

    #[derive(Debug, Error)]
    #[error("App error")]
    struct AppError;
```

examples/use_simple_logging/cmd_args:

```rust
    use clap::{crate_version, AppSettings, Clap};

    #[derive(Clap, Debug)]
    #[clap(version = crate_version!(), setting=AppSettings::ColoredHelp)]
    pub struct CmdArgs {}
```

2021-08-17 19:55 UTC, gcfbn commented
> * how would you like to use the DefaultLogger struct and its write_message method ?

I forgot to replace line 23: `flexi_logger::Logger::try_with_env().unwrap().log_to_stdout().start().unwrap();`
with something like this: `DefaultLogger::initialize_logger().unwrap();`

My idea was similar to this:
>In case when simple_logging is not defined we will have an empty implementation of the configure_logging mehtod.
>The user still has the option to implement his own version of this method.

`write_message` method was meant to be used instead of `error!`, `warn!` etc. if someone would like to implement his own logger that isn't compatible with these macros.


>  
> ```
> fn configure_logging() {
>     #[cfg(feature = "simple_logging")] {
>       flexi_logger::Logger::try_with_env().unwrap().log_to_stdout().start().unwrap();
>       trace!("Default logger initialized");
>     }
> }
> ```
>

This way is better, because user doesn't get an error if they don't add `simple_logging` feature to cargo.toml

2021-08-18 05:25 UTC, pdodev commented
```sh
❯ cargo check
    Checking utils v0.1.0 (/home/pdo/_pawel/Rust/_2/learning_rust/utils)
error[E0432]: unresolved import `flexi_logger`
 --> src/application_runner.rs:3:5
  |
3 | use flexi_logger::FileSpec;
  |     ^^^^^^^^^^^^ use of undeclared crate or module `flexi_logger`

```

2021-08-18 05:33 UTC, pdodev commented on utils/Cargo.toml
> +path = "examples/use_simple_logging/lib.rs"
you can remove this line

2021-08-18 05:34 UTC, pdodev commented on utils/Cargo.toml
> +path = "examples/use_simple_logging/lib.rs"
you can remove this line

2021-08-18 05:36 UTC, pdodev commented on utils/examples/use_simple_logging/lib.rs
> +struct AppError;
rename lib.rs -> main.rs

2021-08-18 05:40 UTC, pdodev commented on utils/src/lib.rs
> +
remove this code and use 'use' statement.
e.g.: add this code:
```rust
use log::{error,info,trace};
```
to application_runner.rs

2021-08-18 05:55 UTC, pdodev commented on utils/Cargo.toml
> +[[example]]
add this line to this section:
```toml
required-features = [ "simple_logging" ]
```

2021-08-18 05:55 UTC, pdodev commented on utils/Cargo.toml
> +path = "examples/use_simple_logging/lib.rs"
you can remove this line

2021-08-19 04:10 UTC, merged