gcfbn graph_file_generator
gcfbn/learning_rust pull request #52
Opened 2021-07-11 14:04 UTC by gcfbn

Issue #45

2021-07-11 15:15 UTC, pdodev requested changes
Tych plików nie trzeba przechowywać w repozytorium - lepiej jest je generować 'on demand':

graphs/algorithms/tests/benchmarks_data/1000_nodes.txt 
graphs/algorithms/tests/benchmarks_data/10000_nodes.txt 
graphs/algorithms/tests/benchmarks_data/100000_nodes.txt 

Patrz zmiany w **makefile**-u

2021-07-11 15:15 UTC, pdodev commented on graphs/makefile
> +	cargo run -- gfg algorithms/tests/benchmarks_data/100000_nodes.txt 100000 300000 100
Spróbuj coś takiego (potem to jeszcze uprościmy)
```
benchmarks_data: generate_graph_1000_nodes generate_graph_10000_nodes generate_graph_100000_nodes

generate_graph_1000_nodes: 1000_nodes.txt.generated
	@mkdir -p algorithms/benches/data

1000_nodes.txt.generated:
	cargo run -- gfg algorithms/benches/data/1000_nodes.txt 1000 3000 100 && touch 1000_nodes.txt.generated

generate_graph_10000_nodes: 10000_nodes.txt.generated
	@mkdir -p algorithms/benches/data

10000_nodes.txt.generated:
	cargo run -- gfg algorithms/benches/data/10000_nodes.txt 10000 30000 100 && touch 10000_nodes.txt.generated

generate_graph_100000_nodes: 100000_nodes.txt.generated
	@mkdir -p algorithms/benches/data

100000_nodes.txt.generated:
	cargo run -- gfg algorithms/benches/data/100000_nodes.txt 100000 300000 100 && touch 100000_nodes.txt.generated
```

2021-07-11 15:22 UTC, pdodev commented on graphs/runner/src/graph_file_generator.rs
> +    let mut output = File::create(&parameters.graph_file)?;
Jeżeli parameters.graph_file ma postać `a/b/`graph_file.txt, a katalog `a/b` nie istnieje, to go utwórz.
Pomoże to nam uprościć makefile-a (-> `mkdir -p`)

2021-07-13 06:06 UTC, pdodev commented on graphs/runner/src/main.rs
> +}
To już jest raczej krok za daleko. Jeżeli użytkownik chce mieć plik z rozszerzeniem np. .zzz to dlaczego mu na to nie pozwalać ?

2021-07-13 06:10 UTC, pdodev commented on graphs/runner/src/graph_file_generator.rs
> +    create_directory_if_necessary(parameters.graph_file.clone())?;
Modyfikowanie przekazywanej ścieżki to szczegół implementacyjny, dlatego lepiej to schować:
dlatego tutaj:
```rust
create_directory_if_necessary(parameters.graph_file)?;
```
a dalej:
```rust
fn create_directory_if_necessary(path: &PathBuf) -> ioResult<()> {
    let mut path = path.clone();
    path.pop();
    fs::create_dir_all(path)
}
```

2021-07-13 06:11 UTC, pdodev commented on graphs/runner/src/graph_file_generator.rs
> +}
```rust
fn create_directory_if_necessary(path: &PathBuf) -> ioResult<()> {
    let mut path = path.clone();
    path.pop();
    fs::create_dir_all(path)
}
```

2021-07-13 06:22 UTC, pdodev commented on graphs/runner/src/main.rs
> +    let nodes_count = nodes_count.parse::<u32>()?;
Może warto dodać bardziej precyzyjny komunikat błędu:
```rust
use anyhow::Context;
```
```rust
let nodes_count = nodes_count
        .parse::<u32>()
        .with_context(|| format!("it must be a number -> '{}'", nodes_count))?;
```

Np. 
```
cargo run -p runner -- gfg --graph-file aaa.txt --nodes-count 4a --edges-count 5 --max-weight 100
```
zamiast:

```
error: Invalid value for '--nodes-count <nodes-count>': invalid digit found in string
```

będziesz miał:

```
error: Invalid value for '--nodes-count <nodes-count>': it must be a number -> '4a'
```

2021-07-13 06:24 UTC, pdodev requested changes
Popatrz jeszcze na to:
```
❯ cargo run -p runner -- gfg --graph-file aaa.txt --nodes-count 4 --edges-count 3 --max-weight 100
    Finished dev [unoptimized] target(s) in 0.02s
     Running `target/debug/runner gfg --graph-file aaa.txt --nodes-count 4 --edges-count 3 --max-weight 100`
thread 'main' panicked at 'attempt to subtract with overflow', runner/src/graph_file_generator.rs:73:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

2021-07-13 13:46 UTC, pdodev commented on graphs/runner/src/graph_file_generator.rs
> +    let mut output = File::create(&parameters.graph_file)?;
Zamiast bail-a zwróć błąd. Możesz zdefiniować do tego enum-a GraphFileGeneratorError (przyda się też w unit-testach) jak również
```rust
#[derive(Error, Debug)]
pub enum RunnerError {
     GraphFileGeneratorError
}
```

2021-07-13 13:56 UTC, pdodev commented on graphs/runner/src/main.rs
> +}
Nie jestem przekonany do tych unit-testów. Nawet nie o to chodzi, że musisz powtarzać w nich stringi zwracane w błędach. Problem polega bardziej na tym, że nie ma testów akceptacyjnych, a jeżeli one by się pojawiły to te testy okazałyby się niepotrzebne (ponieważ duplikowałby to co już jest sprawdzane w testach akceptacyjnych).

2021-07-13 14:26 UTC, gcfbn commented on graphs/runner/src/main.rs
> +}
Okej, rzeczywiście po dodaniu enum-ów z rodzajami błędów powinno być łatwiej napisać testy akceptacyjne.

2021-07-13 14:40 UTC, pdodev reviewed
Proponuję unieważnić tego PR-a.
Wszystkie zmiany z twojego branch-a (WIP_) zmergowałem do nowego branch-a: graph_file_generator

Będzie jeszcze bardzo dużo zmian :-), dlatego następne PR-y będziemy robić do tego branch-a (graph_file_generator), a nie od razu do main-a.

2021-07-13 19:03 UTC, gcfbn commented
Zmergowano zmiany do `graph_file_generator`

2021-07-13 19:03 UTC, closed without merging