`runner` - error enums and first attempt to acceptance tests
gcfbn/learning_rust pull request #55
Opened 2021-07-15 17:01 UTC by gcfbn

2021-07-15 17:35 UTC, gcfbn commented
#587dda6 miał już pójść do osobnego PR, za szybko zrobiłem pusha

2021-07-15 17:58 UTC, pdodev commented on graphs/runner/src/errors.rs
> +         nodes `{nodes_count}`"
"`{edges_count}` edges is not enough to generate connected graph with `{nodes_count}` nodes"

2021-07-15 17:59 UTC, pdodev commented on graphs/runner/src/graph_file_generator.rs
> +pub type Result<T, E = GraphFileGeneratorError> = std::result::Result<T, E>;
to możesz przenieść do pliku errors.rs

2021-07-15 18:02 UTC, pdodev commented on graphs/runner/src/graph_file_generator.rs
> +            "given number of edges `28` is to small to generate connected graph containing given number of nodes `30`";
Lepiej jest sprawdzać typ błędu: GraphFileGeneratorError

2021-07-15 18:04 UTC, pdodev commented on graphs/runner/src/main.rs
> +    mod subcommand_graph_file_generator {
Cały ten moduł (tests::subcommand_graph_file_generator) przenieś do cli.rs

2021-07-15 18:06 UTC, pdodev commented on graphs/runner/src/graph_file_generator.rs
> +use crate::errors::GraphFileGeneratorError;
Zmień nazwę tego pliku: graph_file_generator.rs -> generate_graph.rs. 
Obecna nazwa może sugerować, że plik zawiera implementację podkomendy GraphFileGenerator

2021-07-15 18:08 UTC, pdodev commented on graphs/runner/src/graph_file_generator.rs
>      if !possible_to_create_connected_graph(parameters) {
possible_to_create_connected_graph -> is_possible_to_create_connected_graph

2021-07-15 18:09 UTC, pdodev requested changes
Kilka drobiazgów jest do zmiany

2021-07-15 19:25 UTC, gcfbn commented on graphs/runner/src/main.rs
> +    mod subcommand_graph_file_generator {
Ostatecznie testy akceptacyjne wrzuciłem do tests/graph_file_generator_subcommands

2021-07-16 16:23 UTC, pdodev approved these changes

2021-07-16 16:24 UTC, merged